config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :workouts
  resources :runs
  get 'pages/index'
  get 'pages/portfolio'
  get 'pages/contact'
  get 'pages/extra'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/run.rb
class Run < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    before_action :init_nav

    def init_nav
    
        if authenticate_user! || user_signed_in?
            @userName = current_user.first + " " + current_user.last
        end 

    end




    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first, :last, :private])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first, :last, :private])
        
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def portfolio


  end

  def contact
  end

  def extra
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: %i[ show edit update destroy ]
  

  # GET /runs or /runs.json
  def index
    @runs = Run.all
  end

  # GET /runs/1 or /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs or /runs.json
  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to run_url(@run), notice: "Run was successfully created." }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1 or /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to run_url(@run), notice: "Run was successfully updated." }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1 or /runs/1.json
  def destroy
    @run.destroy

    respond_to do |format|
      format.html { redirect_to runs_url, notice: "Run was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def run_params
      params.require(:run).permit(:name, :hours, :miles, :dateRan, :user_id)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]
  

  # GET /workouts or /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1 or /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully created." }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:name, :hours, :dateWorked, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid bg-dark ">
      <%= link_to "Fitness App", root_path, class: "navbar-brand text-light" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> 
      <div class="collapse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active text-light" %>
          </li>
          <li class="nav-item ">
            <%= link_to "Portfolio", pages_portfolio_path, class: "nav-link active text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", pages_contact_path, class: "nav-link active text-light" %>
          </li>
        </ul>
      </div>

    <% if user_signed_in? %>
      <div class="d-flex flex-row-reverse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav float-end">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> <%= @userName %> </a>
            <ul class="dropdown-menu bg-dark">
              <li><%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item text-light", id: "custNavLink" %></li>
              <li><%= link_to "Learn the Truth", "https://theflatearthsociety.org/home/index.php", class: "dropdown-item text-light", id: "custNavLink" %></li>
              <li><%= button_to( "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item text-danger ", id: "custNavLink  ") %></li>
            </ul>
          </li>
        </ul>
      </div> 
      <% else %> 
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-success" %>
      <% end %>


    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous" defer></script>
    <!-- script tag used for drop down, js gem may be old version -->
  </head>
  
  <div class="container">
  <body>
  
    <%= render "/layouts/nav", run: @nav %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
    
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/extra.html.erb
<h1>Pages#extra</h1>
<p>Find me in app/views/pages/extra.html.erb</p>

app/views/pages/index.html.erb
<div class="row " id="topPage">
    
    <div class="col imageContainer">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active bg-dark">
                    <%= image_tag("/assets/motiv4-7f5f73d74502bd68e0da355a974b1f07975a6e666b72c829c468916a7c734d8f.png", class: "d-block w-100 mh-75 rounded")%> 
                </div>
                <div class="carousel-item bg-dark">
                    <%= image_tag("/assets/motiv1-42a9431a670d8489322f053608fd516a05db4ff9564b1617fbaeec2e9bf8f5ee.png", class: "d-block w-100 mh-75 rounded")%> 
                </div>
                <div class="carousel-item bg-dark">
                    <%= image_tag("/assets/motiv2-646cbae652fdf7934231bc766f8f72143564ef62a51b8fd1bd41932db46da94d.png", class: "d-block w-100a mh-75 rounded")%> 
                </div>
                <div class="carousel-item bg-dark">
                    <%= image_tag("/assets/motiv3-29a0726e15574181bfc0462de2c855da07cafd5535c90fbf5d2af202e6f959d7.png", class: "d-block w-100 mh-75 rounded")%> 
                </div>
            </div>
        </div>
        
        <% if user_signed_in? %>
            <h1 class="imageTagContentTop"> Welcoom: <%= @userName%> </h1>
        <% else %>
            <h1 class="imageTagContentTop"> New to the app? Sign Up <%= link_to "Here", new_user_registration_path, class: "nav-link" %></h1>
        <% end %>
        <h1 class="imageTagContentBottom">Today is: <%= Date.current.to_formatted_s(:long_ordinal) %></h1>
        
    </div>

</div>

<div class="row mt-2" id="content">
    <div class="col m-2 bg-dark rounded"> 
        <div class="col m-2 text-center"> <h2 class="m-2 mt-4 pt-2 pb-2 text-light">Yesterdays Prgress: <%= Date.yesterday.to_formatted_s(:long_ordinal) %> </h2> </div>
        <div class="col m-2 text-center"> <h2 class="m-2 mt-4 pt-2 pb-2 text-light">Todays goal is: User_daily_goal </h2> </div>
    </div>
    <div class="col m-2 border border-dark rounded bg-dark">
    
    <%= link_to runs_path, class: "text-decoration-none  m-2 button", :action => 'go' do %>
        <div class="col text-center pt-2 pb-2" id="custButton">
            <h2 class="text-light">Track Recent Run/Jog</h2>
        </div>
    <% end %>
    
    <%= link_to workouts_path, class: "text-decoration-none  m-2", :action => 'go' do %>
        <div class="col text-center pt-2 pb-2" id="custButton">
            <h2 class="text-light">Track Recent Workout</h2>
        </div>
    <% end %>

    </div>
</div>

<div class="row mt-3">

    

</div>

app/views/pages/portfolio.html.erb
<div class="row">
    <div class="col">
        <p>Account Name: <%= current_user.first %> <%= current_user.last %> </p>
        <p>Account Email: <%= current_user.email %> </p>
        <% if current_user.private %>
            <p>Privacy: Account is Private </p>
        <% else %>
            <p>Privacy: Account is Public </p>
        <% end %>
        <p> Account Created at: <%= current_user.created_at.to_formatted_s(:long_ordinal) %> </p>
    </div>

    <div class="col">
        <div class="row">
            <div class="col">
                <%= link_to "Runs", runs_path, class: "nav-link" %>
            </div>

            <div class="col">
                <%= link_to "Workouts", workouts_path, class: "nav-link" %>
            </div>
        </div>
    </div>

</div>

<div class="row" >
    
</div>

app/views/runs/_form.html.erb
<%= form_with(model: run) do |form| %>
  <% if run.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
        <% run.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "John's nth Run" %>
  </div>

  <div>
    <%= form.label :hours, style: "display: block" %>
    <%= form.number_field :hours, in: 1.00..1000.00, placeholder: "1.2" %>
  </div>

  <div>
    <%= form.label :miles, style: "display: block" %>
    <%= form.number_field :miles, in: 1.00..1000.00, placeholder: "8.3" %>
  </div>

  <div>
    <%= form.label :dateRan, style: "display: block" %>
    <%= form.date_field :dateRan, placeholder: DateTime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/runs/_run.html.erb
<div id="<%= dom_id run %>">
  <p>
    <strong>Name:</strong>
    <%= run.name %>
  </p>

  <p>
    <strong>Hours:</strong>
    <%= run.hours %>
  </p>

  <p>
    <strong>Miles:</strong>
    <%= run.miles %>
  </p>

  <p>
    <strong>Dateran:</strong>
    <%= run.dateRan %>
  </p>

</div>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render "form", run: @run %>

<br>

<div>
  <%= link_to "Show this run", @run %> |
  <%= link_to "Back to runs", runs_path %>
</div>

app/views/runs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Runs</h1>

<div id="runs">
  <% @runs.each do |run| %>
    <%= render run %>
    <p>
      <%= link_to "Show this run", run %>
    </p>
  <% end %>
</div>

<%= link_to "New run", new_run_path %>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render "form", run: @run %>

<br>

<div>
  <%= link_to "Back to runs", runs_path %>
</div>

app/views/runs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @run %>

<div>
  <%= link_to "Edit this run", edit_run_path(@run) %> |
  <%= link_to "Back to runs", runs_path %>

  <%= button_to "Destroy this run", @run, method: :delete %>
</div>

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :hours, style: "display: block" %>
    <%= form.text_field :hours %>
  </div>

  <div>
    <%= form.label :dateWorked, style: "display: block" %>
    <%= form.date_field :dateWorked %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <p>
    <strong>Name:</strong>
    <%= workout.name %>
  </p>

  <p>
    <strong>Hours:</strong>
    <%= workout.hours %>
  </p>

  <p>
    <strong>Dateworked:</strong>
    <%= workout.dateWorked %>
  </p>

</div>

app/views/workouts/_workoutshow.html.erb
<div id="<%= dom_id workout %>">
  <p>
    <strong>Name:</strong>
    <%= workout.name %>
  </p>

</div>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Show this workout", @workout %> |
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workouts</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Show this workout", workout %>
    </p>
  <% end %>
</div>

<%= link_to "New workout", new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout %>

<div>
  <%= link_to "Edit this workout", edit_workout_path(@workout) %> |
  <%= link_to "Back to workouts", workouts_path %>

  <%= button_to "Destroy this workout", @workout, method: :delete %>
</div>